import { Play } from "lucide-react";

export function VoiceNote() {
  return (
    <div className="block absolute top-44 md:top-24 right-0 md:-right-16 bg-purple-400/20 backdrop-blur-xs rounded-3xl">
      <div className="flex items-start gap-2.5">
        <div className="flex flex-col gap-2.5 w-full max-w-[320px] leading-1.5 p-4 bg-neutral-secondary-soft rounded-e-base rounded-es-base">
          <div className="flex items-center space-x-1.5 rtl:space-x-reverse">
            <button
              className="inline-flex self-center items-center text-body hover:text-heading opacity-50 border border-white text-white rounded-full p-1.5"
              type="button"
            >
              <Play size={16} strokeWidth={2} />
            </button>
            <svg
              aria-hidden="true"
              opacity={0.5}
              className="w-[145px] md:w-[185px] md:h-[40px] text-purple-700"
              viewBox="0 0 185 40"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect
                y="17"
                width="3"
                height="6"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="7"
                y="15.5"
                width="3"
                height="9"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="21"
                y="6.5"
                width="3"
                height="27"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="14"
                y="6.5"
                width="3"
                height="27"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="28"
                y="5"
                width="3"
                height="30"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="35"
                y="3"
                width="3"
                height="34"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="42"
                y="5.5"
                width="3"
                height="29"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="49"
                y="10"
                width="3"
                height="20"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="56"
                y="13.5"
                width="3"
                height="13"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="63"
                y="16"
                width="3"
                height="8"
                rx="1.5"
                fill="#6B7280"
                className="fill-white"
              />
              <rect
                x="70"
                y="12.5"
                width="3"
                height="15"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="77"
                y="3"
                width="3"
                height="34"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="84"
                y="3"
                width="3"
                height="34"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="91"
                y="0.5"
                width="3"
                height="39"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="98"
                y="0.5"
                width="3"
                height="39"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="105"
                y="2"
                width="3"
                height="36"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="112"
                y="6.5"
                width="3"
                height="27"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="119"
                y="9"
                width="3"
                height="22"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="126"
                y="11.5"
                width="3"
                height="17"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="133"
                y="2"
                width="3"
                height="36"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="140"
                y="2"
                width="3"
                height="36"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="147"
                y="7"
                width="3"
                height="26"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="154"
                y="9"
                width="3"
                height="22"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="161"
                y="9"
                width="3"
                height="22"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="168"
                y="13.5"
                width="3"
                height="13"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="175"
                y="16"
                width="3"
                height="8"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="182"
                y="17.5"
                width="3"
                height="5"
                rx="1.5"
                fill="#E5E7EB"
                className="fill-quaternary"
              />
              <rect
                x="66"
                y="16"
                width="8"
                height="8"
                rx="4"
                fill="currentColor"
              />
            </svg>
            <span className="inline-flex self-center items-center text-sm font-medium text-heading opacity-50 text-white">
              3:42
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
